version: '2'
services:
    gonzahipsterone-app:
        image: gonzahipsterone
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gonzahipsterone-postgresql:5432/gonzahipsterone
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gonzahipsterone-elasticsearch:9300
        ports:
            - 8080:8080
    gonzahipsterone-postgresql:
        extends:
            file: postgresql.yml
            service: gonzahipsterone-postgresql
    gonzahipsterone-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gonzahipsterone-elasticsearch
