version: '2'
services:
    gonzahipsterone-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/gonzahipsterone/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=gonzahipsterone
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
